/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulador;

/**
 *
 * @author Alex
 */
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
public class Simulador extends javax.swing.JDialog {

    /**
     * Creates new form Simulador
     */
    private ListaLigada ll;
    private int total;
    private ArrayList<JTextField> inf;
    private ArrayList<JComboBox> combs;
    private ArrayList<JTextField> data;
    private String[][] filas;
    public Simulador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        total=0;
        inf=new ArrayList<JTextField>();
        combs=new ArrayList<JComboBox>();
        data=new ArrayList<JTextField>();
        ll=new ListaLigada();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        agregar = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        addfield = new javax.swing.JButton();
        formulario = new javax.swing.JPanel();
        aceptar = new javax.swing.JButton();
        paneAdd = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tablas = new javax.swing.JComboBox<>();
        paf = new javax.swing.JPanel();
        accept = new javax.swing.JButton();
        agregarinfo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        deletebox = new javax.swing.JComboBox<>();
        delete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tablebox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        campos = new javax.swing.JComboBox<>();
        metodos = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        datos = new javax.swing.JTable();
        show = new javax.swing.JButton();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarMouseClicked(evt);
            }
        });

        jLabel1.setText("Nombre de la Tabla");

        name.setText("TABLA");

        addfield.setText("Agregar Campo >");
        addfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfieldActionPerformed(evt);
            }
        });

        formulario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        formulario.setAutoscrolls(true);

        javax.swing.GroupLayout formularioLayout = new javax.swing.GroupLayout(formulario);
        formulario.setLayout(formularioLayout);
        formularioLayout.setHorizontalGroup(
            formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        formularioLayout.setVerticalGroup(
            formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(aceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(formulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addfield)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addfield))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(aceptar)
                .addContainerGap())
        );

        agregar.addTab("Crear", jPanel1);

        jLabel5.setText("Nombre de la Tabla");

        tablas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pafLayout = new javax.swing.GroupLayout(paf);
        paf.setLayout(pafLayout);
        pafLayout.setHorizontalGroup(
            pafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
        pafLayout.setVerticalGroup(
            pafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        accept.setText("Aceptar");
        accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptActionPerformed(evt);
            }
        });

        agregarinfo.setText("Agregar Info");
        agregarinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarinfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneAddLayout = new javax.swing.GroupLayout(paneAdd);
        paneAdd.setLayout(paneAddLayout);
        paneAddLayout.setHorizontalGroup(
            paneAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAddLayout.createSequentialGroup()
                .addGroup(paneAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneAddLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tablas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneAddLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(paf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneAddLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(accept)
                        .addGap(51, 51, 51)
                        .addComponent(agregarinfo)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        paneAddLayout.setVerticalGroup(
            paneAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(paneAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accept)
                    .addComponent(agregarinfo)))
        );

        agregar.addTab("Agregar", paneAdd);

        jLabel2.setText("Tablas");

        deletebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        delete.setText("Borrar");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delete)
                    .addComponent(deletebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(deletebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(delete)
                .addGap(47, 47, 47))
        );

        agregar.addTab("Eliminar", jPanel3);

        jLabel3.setText("Tablas");

        tablebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tablebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableboxActionPerformed(evt);
            }
        });

        jLabel4.setText("Ordenar Por");

        metodos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Burbuja", "Burbuja con Señal", "Baraja", "Selección Directa", "QuickSort", "ShakerSort", "Inserccion Binaria", "ShellSort" }));
        metodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodosActionPerformed(evt);
            }
        });

        datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(datos);

        show.setText("Mostrar");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(tablebox, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(show))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(campos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(metodos, 0, 1, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tablebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(metodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        agregar.addTab("Mostrar", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agregar)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agregar)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfieldActionPerformed
        // TODO add your handling code here:
        JLabel nom=new JLabel("Nombre del Campo");
        JTextField camp=new JTextField(8);
        JLabel tipo=new JLabel("Tipo");
        String [] lista={"Texto", "Numerico"};
        JComboBox type=new JComboBox(lista);
        formulario.setLayout(new GridLayout(0, 4));
        formulario.add(nom);
        formulario.add(camp);
        formulario.add(tipo);
        formulario.add(type);
        inf.add(camp);
        combs.add(type);
        this.total++;
        this.repaint();
        this.revalidate();
        this.setResizable(true);
    }//GEN-LAST:event_addfieldActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        Tabla t=new Tabla(total);
        t.setNombre(name.getText());
        for(int x=0;x<inf.size();x++){
            String nombre=inf.get(x).getText();
            String tipo=combs.get(x).getSelectedItem().toString();
            Campo c=new Campo(nombre, tipo);
            t.setCampos(c);
        }
        ll.agregar(t);
        formulario.removeAll();
        inf.clear();
        paf.removeAll();
        name.setText("");
        this.repaint();
        this.revalidate();
        this.total=0;
    }//GEN-LAST:event_aceptarActionPerformed
    public void llenarComboTablas(){
        ArrayList <Tabla> array = new ArrayList<Tabla>();
        for(Nodo n=ll.getCab();n!=null;n=n.getSiguiente()){
            array.add(n.getDato());
        }
        String [] options = new String[array.size()];
        for(int i = 0; i < array.size(); i++){
            options[i]=array.get(i).getNombre();
        }
        tablas.setModel(new DefaultComboBoxModel(options));
        deletebox.setModel(new DefaultComboBoxModel(options));
        tablebox.setModel(new DefaultComboBoxModel(options));
        this.repaint();
        this.revalidate();
    }
    public void llenarCamposBox(){
        Nodo n=ll.buscar(tablebox.getSelectedItem().toString());
        if(n!=null){
            String [] options = new String[n.getDato().getLength()];
            for(int x=0;x<n.getDato().getLength();x++)
                    options[x]=n.getDato().getCampo(x).getNombre();
            campos.setModel(new DefaultComboBoxModel(options));
        }else
            System.out.println("hay nulidad");
    }
   
    private void agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseClicked
        // TODO add your handling code here:
        llenarComboTablas();
    }//GEN-LAST:event_agregarMouseClicked

    private void tablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablasActionPerformed
        // TODO add your handling code here:
        data.clear();
        paf.setLayout(new GridLayout(0, 2));
        paf.removeAll();
        for(Nodo n=ll.getCab();n!=null;n=n.getSiguiente()){
            if(n.getDato().getNombre().equals(tablas.getSelectedItem().toString()))
                for(int x=0;x<n.getDato().getLength();x++){
                    String nombre=n.getDato().getCampo(x).getNombre();
                    JLabel jl=new JLabel(nombre);
                    JTextField tf=new JTextField(15);
                    data.add(tf);
                    paf.add(jl);
                    paf.add(tf);
                }
        }
        tablas.setEnabled(false);
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_tablasActionPerformed
    private void llenarTabla(){
        Nodo n=ll.buscar(tablebox.getSelectedItem().toString());
        if(n!=null){
            String [] encabezado = new String[n.getDato().getLength()];
            for(int x=0;x<encabezado.length;x++)
                    encabezado[x]=n.getDato().getCampo(x).getNombre();
            DefaultTableModel modelo=new DefaultTableModel(encabezado,0);
            datos.setModel(new DefaultTableModel());
            String dats[]=new String[encabezado.length];
            for(NodoDoble nd=n.getDato().getLista().getInicio();nd!=null;nd=nd.getSiguiente()){
                for(int x=0;x<n.getDato().getLength();x++)
                    dats[x]=nd.getDato().getDato(x);
                modelo.addRow(dats);
            }
            datos.setModel(modelo);
            
        }
    }
    private void agregarinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarinfoActionPerformed
        // TODO add your handling code here:
        Fila f;
        for(Nodo n=ll.getCab();n!=null;n=n.getSiguiente()){
            if(n.getDato().getNombre().equals(tablas.getSelectedItem().toString())){
                f= new Fila(n.getDato().getLength());
                for(int x=0;x<n.getDato().getLength();x++){
                    f.setDato(data.get(x).getText());
                    n.getDato().setDatos(data.get(x).getText());
                    data.get(x).setText("");
                }
                n.getDato().setFila(f);
            }
        }
    }//GEN-LAST:event_agregarinfoActionPerformed

    private void acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptActionPerformed
        // TODO add your handling code here:
        tablas.setEnabled(true);
        paf.removeAll();
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_acceptActionPerformed

    private void tableboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableboxActionPerformed
        // TODO add your handling code here:
        llenarCamposBox();
    }//GEN-LAST:event_tableboxActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        llenarTabla();
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_showActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        Nodo n=ll.buscar(deletebox.getSelectedItem().toString());
        String[] opciones = {"Si", "No"};
 
        int opcion = JOptionPane.showOptionDialog(
                               null                             //componente
                             , "Estas seguro que deseas ELIMINAR\nesta tabla?"            // Mensaje
                             , "Opciones Personalizada"         // Titulo en la barra del cuadro
                             , JOptionPane.DEFAULT_OPTION       // Tipo de opciones
                             , JOptionPane.INFORMATION_MESSAGE  // Tipo de mensaje (icono)
                             , null                             // Icono (ninguno)
                             , opciones                         // Opciones personalizadas
                             , null                             // Opcion por defecto
                           );
        if(opcion==0)
            if(n!=null){
                ll.eliminar(n.getDato());
                JOptionPane.showMessageDialog(null, "Eliminacion exitosa");
                llenarComboTablas();
            }else JOptionPane.showMessageDialog(null, "No se pudo eliminar");
    }//GEN-LAST:event_deleteActionPerformed

    private void metodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodosActionPerformed
        // TODO add your handling code here:
        if(metodos.getSelectedItem().toString().equals("Burbuja")){
            Nodo n=ll.buscar(tablebox.getSelectedItem().toString());
            n.getDato().burbuja(campos.getSelectedIndex());
        }
        if(metodos.getSelectedItem().toString().equals("Burbuja con Señal")){
            System.out.println("Entre a if");
            Nodo n=ll.buscar(tablebox.getSelectedItem().toString());
            n.getDato().burbujaSenal(campos.getSelectedIndex());
        }
        if(metodos.getSelectedItem().toString().equals("Selección Directa")){
            //System.out.println("Entre a if");
            Nodo n=ll.buscar(tablebox.getSelectedItem().toString());
            n.getDato().seleccionDirecta(campos.getSelectedIndex());
        }
        if(metodos.getSelectedItem().toString().equals("Baraja")){
            //System.out.println("Entre a if");
            Nodo n=ll.buscar(tablebox.getSelectedItem().toString());
            n.getDato().baraja(campos.getSelectedIndex());
        }
        if(metodos.getSelectedItem().toString().equals("QuickSort")){
            JOptionPane.showMessageDialog(null, "Metodo muy \"talachudo\"\npara implementar");
        }
        if(metodos.getSelectedItem().toString().equals("ShakerSort")){
            JOptionPane.showMessageDialog(null, "Metodo muy no implementado");;
        }
        if(metodos.getSelectedItem().toString().equals("Inserccion Binaria")){
            JOptionPane.showMessageDialog(null, "Metodo muy implementable\n en listas ligadas");
            
        }
        if(metodos.getSelectedItem().toString().equals("ShellSort")){
            JOptionPane.showMessageDialog(null, "Metodo muy implementable\n en listas ligadas");
        }
        llenarTabla();
    }//GEN-LAST:event_metodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Simulador dialog = new Simulador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept;
    private javax.swing.JButton aceptar;
    private javax.swing.JButton addfield;
    private javax.swing.JTabbedPane agregar;
    private javax.swing.JButton agregarinfo;
    private javax.swing.JComboBox<String> campos;
    private javax.swing.JTable datos;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox<String> deletebox;
    private javax.swing.JPanel formulario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JComboBox<String> metodos;
    private javax.swing.JTextField name;
    private javax.swing.JPanel paf;
    private javax.swing.JPanel paneAdd;
    private javax.swing.JButton show;
    private javax.swing.JComboBox<String> tablas;
    private javax.swing.JComboBox<String> tablebox;
    // End of variables declaration//GEN-END:variables
}
